version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install awscli cfn-lint
  build:
    commands:
      - ./generate_cf_deploy.sh $ENV
      
artifacts:
  files:
    - main.yaml
    - deploy.json