AWSTemplateFormatVersion: 2010-09-09
Description: AWS 3 Tier Application

Parameters:
  Env:
    Type: String
  
  CfTemplatesBucket:
    Type: String

Resources:
  CoreStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join [ '', ["https://", !Ref CfTemplatesBucket, ".s3.amazonaws.com/core.yaml"] ]
      TimeoutInMinutes: 10
      Parameters:
        Env: !Ref Env

  WebTierStack:
    DependsOn: CoreStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${CfTemplatesBucket}.s3.amazonaws.com/web-tier.yaml"
      TimeoutInMinutes: 10
      Parameters:
        Env: !Ref Env

  # MiddlewareTierStack:
  #   DependsOn:
  #     - CoreStack
  #     - WebTierStack
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: "https://three-tier-app-artifacts-threetierappartifactsbuc-wlhd17cqtjja.s3.amazonaws.com/middleware-tier.yaml"
  #     TimeoutInMinutes: 10

  # DatabaseTierStack:
  #   DependsOn:
  #     - CoreStack
  #     - MiddlewareTierStack
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: "https://three-tier-app-artifacts-threetierappartifactsbuc-wlhd17cqtjja.s3.amazonaws.com/database-tier.yaml"
  #     TimeoutInMinutes: 10
