AWSTemplateFormatVersion: 2010-09-09
Description: AWS 3 Tier Application

Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/16"
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: "default"
      Tags:
        - Key: "Name"
          Value: "3-tier-app-vpc"

Outputs:
  VpcId:
    Value: !GetAtt Vpc.VpcId
