AWSTemplateFormatVersion: 2010-09-09
Description: Three Tier App Pipeline Template

Parameters:
  Env:
    Type: String
  
  CfTemplatesBucket:
    Type: String

  GithubOwner:
    Type: String
    Default: edgarp-dev
    AllowedPattern: "[A-Za-z0-9-]+"

  GithubRepo:
    Type: String
    Default: 3-tier-app-aws
    AllowedPattern: "[A-Za-z0-9-]+"

  GithubBranch:
    Type: String
    Default: main
    AllowedPattern: "[A-Za-z0-9-_]+"

Resources:
  PipelineArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${Env}-three-tier-app-artifacts-bucket
  
  CFTemplatesCodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${Env}-three-tier-app-cf-templates-codebuild-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowAssumeRole
            Effect: Allow
            Principal:
              Service: "codebuild.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: CodeBuild
                Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                  - "s3:GetObject"
                  - "s3:GetObjectVersion"
                  - "s3:PutObject"
                  - "ecr:BatchCheckLayerAvailability"
                  - "ecr:GetDownloadUrlForLayer"
                  - "ecr:BatchGetImage"
                  - "ecr:GetAuthorizationToken"
                  - "s3:GetBucketAcl"
                  - "s3:GetBucketLocation"
                  - "cloudformation:*"
                  - "iam:PassRole"
                Resource: "*"
          PolicyName: BuildPolicy

  CFTemplatesCodebuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${Env}-three-tier-app-templates-cf-codebuild
      Artifacts:
        Type: CODEPIPELINE
      ServiceRole: !GetAtt CFTemplatesCodeBuildRole.Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspecs/cf-templates-buildspec.yaml
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:2.0
        EnvironmentVariables:
          - Name: CfTemplatesBucket
            Type: PLAINTEXT
            Value: !Ref CfTemplatesBucket

  BuildeDeployConfigCodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${Env}-three-tier-app-build-deploy-config-codebuild-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowAssumeRole
            Effect: Allow
            Principal:
              Service: "codebuild.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: CodeBuild
                Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                  - "s3:GetObject"
                  - "s3:GetObjectVersion"
                  - "s3:PutObject"
                  - "ecr:BatchCheckLayerAvailability"
                  - "ecr:GetDownloadUrlForLayer"
                  - "ecr:BatchGetImage"
                  - "ecr:GetAuthorizationToken"
                  - "s3:GetBucketAcl"
                  - "s3:GetBucketLocation"
                  - "cloudformation:*"
                  - "iam:PassRole"
                Resource: "*"
          PolicyName: BuildPolicy

  BuildeDeployConfigCodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${Env}-three-tier-app-build-deploy-config-codebuild
      Artifacts:
        Type: CODEPIPELINE
      ServiceRole: !GetAtt BuildeDeployConfigCodeBuildRole.Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspecs/build-deploy-config-buildpspec.yaml
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:2.0
        EnvironmentVariables:
          - Name: ENV
            Type: PLAINTEXT
            Value: !Ref Env

  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${Env}-three-tier-app-pipeline-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: "codepipeline.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: ThreeTierCodePipelinePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "codebuild:BatchGetBuilds"
                  - "codebuild:StartBuild"
                  - "cloudwatch:*"
                  - "cloudformation:*"
                  - "s3:*"
                  - "iam:PassRole"
                Resource: "*"

  CfnRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub ${Env}-three-tier-app-cfn-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "cloudformation.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AdministratorAccess"

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Location: !Ref PipelineArtifactsBucket
        Type: S3
      Name: !Sub ${Env}-three-tier-app-pipeline
      RestartExecutionOnUpdate: false
      RoleArn: !GetAtt PipelineRole.Arn
      Stages:
        - Name: Source
          Actions:
            - ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: "1"
                Provider: GitHub
              InputArtifacts: []
              Name: Source
              OutputArtifacts:
                - Name: SourceCode
              Configuration:
                Owner: !Ref GithubOwner
                Repo: !Ref GithubRepo
                Branch: !Ref GithubBranch
                PollForSourceChanges: false
                OAuthToken: "{{resolve:ssm:three-tier-app-github-token}}"
              RunOrder: 1
        - Name: Validate
          Actions:
            - InputArtifacts:
                - Name: SourceCode
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              Name: Validate-Templates
              OutputArtifacts:
                - Name: ValidateOuput
              Configuration:
                ProjectName: !Ref CFTemplatesCodebuild
              RunOrder: 2
        - Name: Build
          Actions:
            - InputArtifacts:
                - Name: SourceCode
              ActionTypeId:
                Category: Test
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              Name: Build-Deploy-Config
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: !Ref BuildeDeployConfigCodeBuild
              RunOrder: 3

  GithubWebhook:
    Type: "AWS::CodePipeline::Webhook"
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: "{{resolve:ssm:three-tier-app-github-token}}"
      RegisterWithThirdParty: "true"
      Filters:
        - JsonPath: "$.ref"
          MatchEquals: refs/heads/{Branch}
      TargetPipeline: !Ref Pipeline
      TargetAction: Source
      TargetPipelineVersion: !GetAtt Pipeline.Version
